import Head from 'next/head';
import axios from 'axios';

import styles from '../styles/Home.module.css';
import Nav from '../components/navigation';

export default function Person({ name, species, image }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>JS Frameworks CA</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Nav />
      <main>
        <div>
          <img src={image} alt={name}></img>
          <h2>{name}</h2>
          <p>{species}</p>
          <p></p>
        </div>
      </main>
    </div>
  );
}

export async function getStaticPaths() {
  const getCharacters = async () => {
    const data = await fetch('https://rickandmortyapi.com/api/character');
    const json = await data.json();
    return json.results;
  };

  const allCharacters = await getCharacters();

  const paths = allCharacters.map((character) => {
    return {
      params: {
        id: character.id.toString(),
      },
    };
  });

  return {
    paths,
    fallback: false,
  };
}

export async function getStaticProps({ params }) {
  const fetchCharacters = async () => {
    const data = await fetch(
      `https://rickandmortyapi.com/api/character/${params.id}`
    );
    const json = await data.json();
    return json;
  };

  const foundCharacter = await fetchCharacters();

  return {
    props: foundCharacter,
  };
}
