import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useState, useEffect } from 'react';
import { useRouter } from 'next/router';
import axios from 'axios';
import Nav from '../components/navigation';

export default function Home() {
  const router = useRouter();
  const [characters, setCharacters] = useState([]);

  const handleOnClick = (id) => {
    router.push(`/${id}`);
  };

  useEffect(() => {
    const getCharacters = async () => {
      const data = await axios.get('https://rickandmortyapi.com/api/character');
      const res = data.data.results;
      setCharacters(res);
    };

    getCharacters();
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>JS Frameworks CA</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Nav />
      <main className={styles.main}>
        <div className={styles.resultsContainer}>
          {characters.map((person) => (
            <div
              className={styles.results}
              key={person.id}
              onClick={() => handleOnClick(person.id)}
            >
              <img src={person.image} alt={person.name}></img>
              <h2>{person.name}</h2>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
